name = "llama2"
author = "Meta"
license = "Meta License"
website = "ai.meta.com"

[service]
provider = "ollama"
base_url = "http://localhost:11434"
model_key = "llama2"

[generation]
temperature = 0.7
top_k = 20
top_p = 0.9
max_tokens = 512
seed = 42
batch = 1
repeat_penalty = 1.15
presence_penalty = 0.0
frequency_penalty = 0.0
threads = 0

[generation.mirostat]
mode = 0
eta = 0.1
tau = 5.0
