name = "Mistral 7B"
author = "MistralAI"
license = ""
website = ""

[service]
provider = "ollama"
base_url = "http://localhost:11434"
model_key = "mistral:7b"

[generation]
temperature = 0.7
top_k = 20
top_p = 0.9
max_tokens = 512
seed = 42
batch = 1
repeat_penalty = 1.15
presence_penalty = 0.0
frequency_penalty = 0.0
threads = 0
stop = ""

[generation.mirostat]
mode = 0
eta = 0.1
tau = 5.0
