name = "Vicuna"
author = "Large Model Systems Organization"
license = ""
website = "https://lmsys.org/"

[service]
provider = "ollama"
base_url = "http://localhost:11434"
model_key = "vicuna:7b-v1.5-16k-q2_K"

[generation]
temperature = 0.0
top_k = 40
top_p = 1.0
max_tokens = 128
seed = -1
batch = 1
threads = 8
presence_penalty = 0.0
frequency_penalty = 1.1
stop = ["<stop>", "\n###"]

#[generation.rope]
#freq_base = 1.0
#freq_scale = 3.2

[generation.mirostat]
mode = 0
eta = 0.1
tau = 5.0
