name = "GPT 3.5"
author = "OpenAI"
license = "Proprietary"
website = "openai.com"

[service]
provider = "openai"
base_url = "https://api.openai.com/v1"
model_key = "gpt-3.5-turbo"

[generation]
temperature = 0.7
top_p = 0.9
max_tokens = 512
seed = 42
repeat_penalty = 1.15
presence_penalty = 0.0
frequency_penalty = 0.0
